const constants = {
    NAME: 'name',
    TITLE: 'title',
    AUTHOR: 'author',
    DESCRIPTION: 'description',
    ITEM_PROP: 'itemprop',
    PROPERTY: 'property',
    CONTENT: 'content',
    KEYWORDS: 'keywords',
    ARTICLE: 'article',
    SOURCE: 'src',
    UNTITLED: 'Untitled article',
    OG_IMAGE: 'og:image',
    OG_SITE_NAME: 'og:site_name',
    OG_DESCRIPTION: 'og:description',
    OG_TYPE: 'og:type',
    OG_AUTHOR: 'og:author',
    TWITTER_SITE: 'twitter:site',
    TWITTER_DESCRIPTION: 'twitter:description',
    META_DESCRIPTION: 'meta[name="description"]',
    HEADER_SELECTOR: 'h1 h2 h3 h4 h5 h6',
    HEADER_WITH_PARAGRAPH: 'p, h1, h2, h3, h4, h5, h6',
    IMAGE_WITH_LOGO: 'img.logo',
    HREF: 'href',
    SIZES: 'sizes',
    ICON: 'icon',
    ICON_SELECTOR: 'link[rel="icon"]',
    APPLE_TOUCH_ICON: 'apple-touch-icon',
    APPLE_ICON_SELECTOR: 'link[rel="apple-touch-icon"]',
    MASK_ICON: 'mask-icon',
    MASK_ICON_SELECTOR: 'link[rel="mask-icon"]',
    DEFAULT_ICON_SIZE: '16x16',
    MEDIUM_BASE_URL: 'https://medium.com/',
};

module.exports = constants;
